# Generated by Django 3.2.2 on 2021-07-05 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlines', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('From', models.CharField(max_length=10)),
                ('To', models.CharField(max_length=10)),
                ('Date', models.DateField(max_length=10)),
                ('Time', models.TimeField(max_length=10)),
                ('Price', models.FloatField(max_length=10)),
                ('class_type', models.CharField(choices=[('Economy Class', 'Economy Class'), ('Business Class', 'Business Class'), ('First class', 'First Class')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_num', models.IntegerField()),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('cvv_num', models.IntegerField()),
                ('fl_det', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.addflight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pass_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('book_time_date', models.DateTimeField(auto_now_add=True)),
                ('fl_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fl_det', to='v1.addflight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
