# Generated by Django 3.2.2 on 2021-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_passenger_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymodel',
            name='card_num',
            field=models.CharField(max_length=100),
        ),
    ]
